# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [6]:
print(np.__version__)
print(np.show_config())

1.24.1
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [184]:
A=np.zeros((10,10))
print("%d bytes" %(A.size*A.itemsize))

800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [9]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [12]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [13]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [15]:
a=np.arange(0,10)
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [19]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [22]:
a=np.array([1,2,0,0,4,0])
print(np.nonzero(a))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [41]:
print(np.random.random(27).reshape(3,3,3))

[[[0.29832359 0.63127097 0.25451624]
  [0.89941154 0.35504318 0.2574104 ]
  [0.13442185 0.71397788 0.26584767]]

 [[0.99637058 0.51517168 0.55417266]
  [0.69386108 0.2052447  0.4718743 ]
  [0.07502451 0.5400798  0.77183468]]

 [[0.40534815 0.17881578 0.41120209]
  [0.57141621 0.66353411 0.59446618]
  [0.64539018 0.70092207 0.35452935]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [53]:
a=np.random.random(100).reshape(10,10)
print("max",a.max())
print("min",a.min())

max 0.9992602212423785
min 0.00047029024958489263


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [67]:
a=np.random.random(30)
#print(a)
#print(np.mean(a))
print("mean",a.mean())

mean 0.5405390392095067


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [186]:
a=np.ones(49).reshape(7,7)
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [92]:
a=np.arange(1,10)
print(np.pad(a,(1,1),'constant',constant_values=(0,0)))
#print(np.pad(a,(1,1)))

[0 1 2 3 4 5 6 7 8 9 0]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [115]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)
"""
output is
nan
False
False
nan
False"""

nan
False
False
nan
False


'\noutput is\nnan\nFalse\nFalse\nnan\nFalse'

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [122]:
a=np.diag([1,2,3,4],k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [164]:
a=np.zeros(64).reshape(8,8)
#a[1::2]=1
a[::2,1::2]=1
a[1::2,::2]=1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [188]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [65]:
a=np.array([[0,1],[1,0]])
print(np.tile(a,(4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [71]:
a=np.arange(25).reshape(5,5)
b=(a-a.min())/(a.max()-a.min())
print(b)

[[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [92]:
np.dtype([('r',np.uint8),('g',np.uint8),('b',np.uint8),('a',np.uint8)])

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [198]:
a=np.arange(1,16).reshape(5,3)
b=np.arange(6).reshape(3,2)
a@b

array([[ 16,  22],
       [ 34,  49],
       [ 52,  76],
       [ 70, 103],
       [ 88, 130]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [100]:
a=np.arange(20)
a[(a>3) & (a<=7)]*=-1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [208]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))  #here -1 refers to axis it will add from last to first

9
10


27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [141]:
z=np.arange(10)
#below are expressions are legal except last one
print(z**z)      # z powerz    3 power 3 =27
print(z<-z)    #z< (-z)  condition false 2 <-2
print(1j*z)   #creating complex number arr
print(z/1/1)  #z converted to float
#not valid expessions
print(2 <<z >>2)  #not valid
#print(z<z>z)  #invalid  to conditions cannot be in one line

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[  0   1   2   4   8  16  32  64 128 256]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [219]:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Murugan K\AppData\Local\Temp\ipykernel_16360\3227561482.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0)/np.array(0))
C:\Users\Murugan K\AppData\Local\Temp\ipykernel_16360\3227561482.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0)//np.array(0))
C:\Users\Murugan K\AppData\Local\Temp\ipykernel_16360\3227561482.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [171]:
a=np.random.uniform(-5,5,10)
print(np.copysign(np.ceil(np.abs(a)),a))

[-1. -3. -2.  3. -4. -5.  5. -3. -3. -4.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [48]:
a=np.arange(3,10)
b=np.arange(5)
print(np.intersect1d(a,b))

[3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [55]:
#np.info(np.seterr)
#print(np.seterr(all="ignore"))
np.ones(3) /0
a=np.seterr(all="ignore")
print(np.seterr(**a))
with np.errstate(all='ignore'):
    print(np.sqrt(-2))

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}
nan


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [220]:
print(np.sqrt(-1) == np.emath.sqrt(-1)) #False  emath sqrt will return complex num 

False


C:\Users\Murugan K\AppData\Local\Temp\ipykernel_16360\2770867030.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [212]:
c=np.datetime64('today','D')-np.timedelta64(1,'D')
print("yesterday",b)
a=np.datetime64('today','D')
print("today",a)
c=np.datetime64('today','D')+np.timedelta64(1,'D')
print("tomorrow",c)

yesterday 2023-01-04
today 2023-01-05
tomorrow 2023-01-06


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [228]:
np.arange('2016-07','2016-08',dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [31]:
A=np.arange(9).reshape(3,3)
B=np.arange(9).reshape(3,3)
np.add(A,B,out=B)
np.divide(A,2,out=A,casting='unsafe')
np.negative(A,out=A)
print(np.multiply(A,B,out=A,casting='unsafe'))

[[  0   0  -4]
 [ -6 -16 -20]
 [-36 -42 -64]]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [50]:
a=np.random.uniform(0,10,10)
#print(a)
print(a-a%1)
print(np.floor(a))
print(np.ceil(a)-1)
print(a.astype(int))
print(np.trunc(a))

[2. 3. 6. 2. 7. 4. 4. 0. 0. 5.]
[2. 3. 6. 2. 7. 4. 4. 0. 0. 5.]
[2. 3. 6. 2. 7. 4. 4. 0. 0. 5.]
[2 3 6 2 7 4 4 0 0 5]
[2. 3. 6. 2. 7. 4. 4. 0. 0. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [238]:
a=np.tile(np.arange(5),(5,1))
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [58]:
iterator=(i for i in range(10))
print(np.fromiter(iterator,int))

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [251]:
np.linspace(0,1,endpoint=False)[1:]

array([0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 , 0.22,
       0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42, 0.44,
       0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64, 0.66,
       0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86, 0.88,
       0.9 , 0.92, 0.94, 0.96, 0.98])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [245]:
a=np.random.random(10)
a.sort()
print('after sorting',a)

after sorting [0.05564537 0.21259254 0.33357381 0.53775227 0.62591738 0.69923614
 0.71035844 0.7242238  0.90252128 0.94641165]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [60]:
A=np.arange(10)
print(np.add.reduce(A))

45


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [74]:
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)
#print(A)
#print(B)
print(np.allclose(A,B))  #with tolarance  assuming shape is same
print(np.array_equal(A,B))  #comparing shape and element wise without tolarance

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [80]:
A=np.ones(20)
A.flags.writeable=False     #read only
#A[0]=10

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [95]:
A=np.random.random((10,2))
X,Y=A[:,0],A[:,1]
R=np.sqrt(X**2+Y**2)   #radius
T=np.arctan2(Y,X)
print(R)
print(T)

[0.73574823 1.01653977 0.51299406 0.98743728 0.54730443 0.60847387
 0.95798766 1.04324107 1.02283257 0.96136166]
[0.87762623 0.38131336 1.44851807 1.41286583 0.42340654 0.95781494
 0.4890378  1.21000087 1.17652017 0.46793285]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [104]:
a=np.random.randint(0,50,10)
#print(a)
#print(a.max())
a[a.argmax()]=0
print(a)

[23 37 33 40 20  1 10 22  9  0]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [120]:
A=np.zeros((5,5),[('x',float),('y',float)])
x=np.linspace(0,1,5)
y=np.linspace(0,1,5)
A['x'],A['y']=np.meshgrid(x,y)
print(A)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [136]:
X=np.arange(8)
Y=X+0.5
C=1/np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [150]:
print("int")
for d_type in [np.int8,np.int32,np.int64]:
    print(np.iinfo(d_type).min)
    print(np.iinfo(d_type).max)
print("float")
for d_type in [np.float32, np.float64]:
    print(np.finfo(d_type).min)
    print(np.finfo(d_type).max)
    print(np.finfo(d_type).eps)

int
-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
float
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


49. How to print all the values of an array? (★★☆) 
(**hint**: np.set_printoptions)

In [168]:
import sys
np.set_printoptions(threshold=sys.maxsize)
x = np.zeros((10, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [177]:
A= np.arange(100)
V=np.random.uniform(0,100)
i=(np.abs(A-V)).argmin()
print(A[i])

16


 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [15]:
a=np.dtype([('position',[('x',float,1),('y',float,1)]),
           ('color',[('r',float,1),('g',float,1),('b',float,1)]
          )])
print(np.zeros(20,a))

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\Murugan K\AppData\Local\Temp\ipykernel_12052\1795953333.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a=np.dtype([('position',[('x',float,1),('y',float,1)]),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [68]:
a=np.random.random((100,2))
#print(a)
x,y=np.atleast_2d(a[:,0],a[:,1])
#print(x)
#print(y)
print(np.sqrt(((x-x.T)**2)+
              ((y-y.T)**2)))

[[0.         0.45124896 0.3095757  ... 0.58904741 0.87111375 0.44143326]
 [0.45124896 0.         0.14336588 ... 0.16000067 0.48354344 0.32969991]
 [0.3095757  0.14336588 0.         ... 0.29433102 0.58630886 0.28499185]
 ...
 [0.58904741 0.16000067 0.29433102 ... 0.         0.47652179 0.47368187]
 [0.87111375 0.48354344 0.58630886 ... 0.47652179 0.         0.48687705]
 [0.44143326 0.32969991 0.28499185 ... 0.47368187 0.48687705 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [87]:
a=np.arange(10,dtype=np.float32)
print(a)
a=a.astype(dtype=np.int32,copy =False)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [114]:
from io import StringIO
s=StringIO("""1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
""")
a=np.genfromtxt(s,delimiter=",",dtype=np.int64)
a

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]], dtype=int64)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [133]:
a=np.arange(10).reshape(5,2)
print("np.denumerate")
for i,v in np.ndenumerate(a):
    print(i,"value",v)
print("np.index")
for i in np.ndindex(a.shape):
    print(i,"value",a[i])

np.denumerate
(0, 0) value 0
(0, 1) value 1
(1, 0) value 2
(1, 1) value 3
(2, 0) value 4
(2, 1) value 5
(3, 0) value 6
(3, 1) value 7
(4, 0) value 8
(4, 1) value 9
np.index
(0, 0) value 0
(0, 1) value 1
(1, 0) value 2
(1, 1) value 3
(2, 0) value 4
(2, 1) value 5
(3, 0) value 6
(3, 1) value 7
(4, 0) value 8
(4, 1) value 9


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [146]:
x,y=np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
d=np.sqrt(x*x+y*y)
sigma,mu=1,0
g=np.exp(-((d-mu)**2/(2*sigma**2)))
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [23]:
num = 10
p = 3
a = np.zeros((num,num))
np.put(a, np.random.choice(range(n*n), p, replace=False),1)
print(a)

[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [35]:
a=np.random.randn(10,10)
b=a-np.mean(a,axis=1,keepdims=True)
print(b)

[[ 0.26906124 -0.04706062 -0.82888663 -1.13751654 -0.18649012  0.81752527
   1.10000902  0.50619187 -0.64048431  0.14765081]
 [ 0.90661026  1.35813292  0.48847472 -0.54540604 -0.46406473 -0.88311173
  -0.28557356 -0.61624079  0.25594975 -0.2147708 ]
 [-0.39025447  1.04991511  0.18725231  0.977731   -1.82807286 -1.59612237
   0.38622748  1.33610324 -1.31634527  1.19356583]
 [-1.54946798  0.26868222 -0.10652868  0.70006718 -0.82713576  1.16707745
   0.8803799  -0.66147109  0.47665827 -0.34826151]
 [ 0.99635749  0.1136217  -0.9138779  -0.16435273  1.41019985 -0.87196049
  -0.90582586  0.90368626  0.40247918 -0.97032749]
 [ 1.95501521  1.13458607  0.60005956  0.44902067 -0.93459111 -1.75154004
   1.01174512 -0.56009528 -0.0570169  -1.84718331]
 [ 0.0939128  -2.10600044  0.35751668  1.34740244 -0.64865596  1.44014127
  -2.21246066 -1.12354202  1.89522244  0.95646345]
 [-0.99447936 -0.95538851 -1.75796788 -0.60324884  0.59541986  0.17321197
   1.13778456  0.64690156  0.94457356  0.81319307]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [42]:
a=np.random.randint(0,20,(5,5))
print(a)
n=1
print(a[a[:,n].argsort()])    # sorting column 1 wise all rows gets realigned based on col 1

[[ 6  4  7  1  7]
 [18 15  2  7  5]
 [15  1 15 19 10]
 [11  6  0 13 19]
 [ 2 14 11  0  4]]
[[15  1 15 19 10]
 [ 6  4  7  1  7]
 [11  6  0 13 19]
 [ 2 14 11  0  4]
 [18 15  2  7  5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [44]:
a=np.random.randint(0,3,(3,10))
print((~a.any(axis=0).any()))        #will return true if all elements are 0's

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [59]:
a=np.random.uniform(0,1,10)
b=0.5
c=a.flat[np.abs(a-b).argmin()]
print(c)

0.5235768792445172


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [97]:
a=np.arange(3).reshape(1,3)
b=np.arange(5,8).reshape(3,1)
it=np.nditer([a,b,None])
for i,j,k in it:
    k[...]=i+j
print(it.operands[2])          #extracting K th storage

[[5 6 7]
 [6 7 8]
 [7 8 9]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [106]:
class NamedArray(np.ndarray):
    def __new__(self,obj,name="no name"):
        self.name=name
        return self
z=NamedArray(np.arange(10),"abc")
print(z.name)

abc


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [112]:
a=np.ones(10)
I=np.random.randint(0,len(a),10)
a=a+np.bincount(I,minlength=len(a))
print(a)

[2. 1. 3. 1. 2. 2. 1. 2. 3. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [127]:
X=np.arange(5)
I=np.array([1,3,5,7,9])
F=np.bincount(I,X)
F

array([0., 0., 0., 1., 0., 2., 0., 3., 0., 4.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [138]:
w,h=16,16
a=np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
b=a[...,0]*256*256+I[...,1]*256+I[...,2]
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [13]:
a=np.arange(64).reshape(2,2,4,4)
#print(a)
print(a.sum(axis=(-2,-1)))

[[120 376]
 [632 888]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [33]:
D=np.random.uniform(0,1,20)
S=np.random.randint(0,10,20)
D_sum=np.bincount(S,weights=D)
D_count=np.bincount(S)
D_mean=D_sum/D_count
print(D_mean)

[0.12423747 0.56773016 0.42081117 0.43460584 0.5073136  0.6738683
 0.67439084 0.60803505 0.69061367]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [40]:
a=np.arange(25).reshape(5,5)
b=np.arange(25,50).reshape(5,5)
dot_p=np.dot(a,b)
#print(dot_p)
print(np.diag(dot_p))

[ 400 1310 2270 3280 4340]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [67]:
a=np.array([1,2,3,4,5])
no_of_zeros=3
#print(a)
no_of_zeros_to_be_added=no_of_zeros*(len(a)-1)
b=np.zeros(len(a)+no_of_zeros_to_be_added)
#print(b)
b[::no_of_zeros+1]=a
print(b)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [81]:
a=np.arange(75).reshape(5,5,3)
b=np.arange(25).reshape(5,5)
print(a*b[:,:,None])

[[[   0    0    0]
  [   3    4    5]
  [  12   14   16]
  [  27   30   33]
  [  48   52   56]]

 [[  75   80   85]
  [ 108  114  120]
  [ 147  154  161]
  [ 192  200  208]
  [ 243  252  261]]

 [[ 300  310  320]
  [ 363  374  385]
  [ 432  444  456]
  [ 507  520  533]
  [ 588  602  616]]

 [[ 675  690  705]
  [ 768  784  800]
  [ 867  884  901]
  [ 972  990 1008]
  [1083 1102 1121]]

 [[1200 1220 1240]
  [1323 1344 1365]
  [1452 1474 1496]
  [1587 1610 1633]
  [1728 1752 1776]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [103]:
A=np.arange(25).reshape(5,5)
#print(A)
A[[0,4]] = A[[4,0]]
print(A)

[[20 21 22 23 24]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [133]:
f=np.random.randint(0,100,(10,3))
c=f.repeat(2,axis=1)   #twice each columns are repeated
F=np.roll(c,-1,axis=1)  #shift column wise
F=F.reshape(len(F)*3,2)    #reshaping matrix to (30,2)
F=np.sort(F,axis=1)
G=F.view(dtype=[('p0',f.dtype),('p1',f.dtype)])
print(np.unique(G))

[( 0, 36) ( 0, 95) ( 2, 20) ( 2, 68) ( 4, 83) ( 4, 95) ( 6,  7) ( 6, 60)
 ( 7, 32) ( 7, 60) ( 7, 66) ( 9, 11) ( 9, 97) (11, 97) (19, 36) (19, 75)
 (20, 68) (26, 62) (26, 77) (30, 32) (30, 45) (32, 45) (32, 66) (36, 75)
 (36, 95) (48, 54) (48, 72) (54, 72) (62, 77) (83, 95)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [145]:
C=np.bincount([1,1,2,3,4,4,6])
print(C)
A=np.repeat(np.arange(len(C)),C)
print(A)
#print(np.bincount(A))

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [164]:
def moving_avg(a,n):
    r=np.cumsum(a,dtype=float)
    r[n:]=r[n:]-r[:-n]
    return r[n-1:]/n    
a=np.arange(20)
r=moving_avg(a,3)
print(r)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [171]:
from numpy.lib import stride_tricks
def rolling(a,n):
    shape=(a.size-n+1,n)
    strides=(a.itemsize,a.itemsize)
    return stride_tricks.as_strided(a,shape=shape,strides=strides)
r=rolling(np.arange(10),3)
print(r)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [187]:
a=np.random.randint(0,20,10)
#print(a)
print(np.logical_not(a))
b=np.random.uniform(-1,1,10)
#print(b)
print(np.negative(b))

[False False False False False False False  True False False]
[-0.58437217 -0.34193313 -0.632855    0.34982938  0.7784353   0.08405388
  0.98228914  0.29874667 -0.13084636 -0.37719705]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [30]:
def distance(P0,P1,p):
    T=P1-P0
    L=(T**2).sum(axis=1)
    U=-((P0[:,0]-p[...,0])*T[:,0]+(P1[:,1]-p[...,1])*T[:,1])/L
    U=U.reshape(len(U),1)
    D=P0+U*T-p
    return np.sqrt((D**2).sum(axis=1))
P0=np.random.uniform(-10,10,(10,2))
P1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,(1,2))
print(distance(P0,P1,p))

[ 7.83136545  8.77795937  8.72069605 15.21812618  8.68136912  1.56055252
 11.86147308 14.04129999  8.11074648  3.31450862]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [33]:
def distance(P0,P1,p):
    T=P1-P0
    L=(T**2).sum(axis=1)
    U=-((P0[:,0]-p[...,0])*T[:,0]+(P1[:,1]-p[...,1])*T[:,1])/L
    U=U.reshape(len(U),1)
    D=P0+U*T-p
    return np.sqrt((D**2).sum(axis=1))
P0=np.random.uniform(-10,10,(10,2))
P1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,(10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[14.0409853   5.76011332  6.13830745  9.23141686  2.25992695  8.63527402
   9.92726223 10.95347371  4.55354984  7.09324548]
 [19.7288709   4.23725409 14.79864802 18.26658616  6.37728397 15.23463585
   6.36334595  9.12623361 16.76302887  8.98102608]
 [14.85695532  3.2885256   9.65010038 12.87225482  4.24696532  9.76975283
   9.01984483  9.27516308  9.21129161  5.59099769]
 [14.37692271  3.4341972   7.76391818 10.96415847  2.69061233  9.01288591
   8.51107414  9.43025848  7.21314047  5.70243894]
 [14.69339926  3.3506858   5.85242565  2.93998518 10.66469682 11.96046002
   4.76348398  8.5453837   4.37290471  5.61262881]
 [14.04793271  7.57644818  7.49834381 10.54157061  4.14819796  8.63457642
  11.90962974 12.16913899  5.23575275  8.19321023]
 [14.75718485  2.54451109  8.33070197 11.57974961  2.70285183  9.41322166
   7.7701772   8.93683298  8.27608344  5.56290605]
 [15.17609849  3.14818454  3.3427078   1.63986235  6.61081322 11.71689489
   5.12321791  9.74562987  3.5657379   6.62850949]


 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [2]:
import numpy as np
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R= Z[z[0]]
print(Z)
print(R)

[[8 2 0 3 1 8 3 5 6 5]
 [0 3 1 8 9 1 2 8 8 4]
 [7 1 0 6 6 0 2 0 7 2]
 [6 9 1 4 4 5 4 1 8 2]
 [8 6 5 7 2 7 1 8 0 3]
 [3 3 0 9 7 0 4 3 8 6]
 [5 5 2 6 6 9 0 7 1 1]
 [2 6 6 4 4 9 3 6 1 7]
 [3 3 3 9 9 5 3 5 3 3]
 [3 9 4 7 2 3 0 1 2 3]]
[[8 2 0 3 1 8 3 5 6 5]
 [0 3 1 8 9 1 2 8 8 4]
 [7 1 0 6 6 0 2 0 7 2]
 [6 9 1 4 4 5 4 1 8 2]]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [59]:
from numpy.lib import stride_tricks
a=np.arange(1,15,dtype=np.uint32)
#print(a)
b=stride_tricks.as_strided(a,(11,4),(4,4))
print(b)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [67]:
a=np.random.uniform(0,1,(10,10))
U,S,V=np.linalg.svd(a)
rank=np.sum(S>1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [80]:
a=np.array([1,2,2,3,3,4,3,4,5,5,5,5,5,5,7])
b=np.bincount(a)
#print(b)
print(np.argmax(b))

5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [90]:
a=np.random.randint(0,5,(10,10))
n=3
i=1+(a.shape[0]-3)
j=1+(a.shape[1]-3)
C=stride_tricks.as_strided(a,shape=(i,j,n,n),strides=a.strides+a.strides)
print(C)

[[[[3 1 1]
   [0 3 2]
   [2 0 4]]

  [[1 1 0]
   [3 2 0]
   [0 4 2]]

  [[1 0 3]
   [2 0 0]
   [4 2 1]]

  [[0 3 4]
   [0 0 4]
   [2 1 4]]

  [[3 4 3]
   [0 4 2]
   [1 4 4]]

  [[4 3 3]
   [4 2 3]
   [4 4 1]]

  [[3 3 2]
   [2 3 4]
   [4 1 0]]

  [[3 2 4]
   [3 4 3]
   [1 0 1]]]


 [[[0 3 2]
   [2 0 4]
   [4 3 4]]

  [[3 2 0]
   [0 4 2]
   [3 4 0]]

  [[2 0 0]
   [4 2 1]
   [4 0 4]]

  [[0 0 4]
   [2 1 4]
   [0 4 2]]

  [[0 4 2]
   [1 4 4]
   [4 2 0]]

  [[4 2 3]
   [4 4 1]
   [2 0 0]]

  [[2 3 4]
   [4 1 0]
   [0 0 4]]

  [[3 4 3]
   [1 0 1]
   [0 4 0]]]


 [[[2 0 4]
   [4 3 4]
   [1 4 1]]

  [[0 4 2]
   [3 4 0]
   [4 1 3]]

  [[4 2 1]
   [4 0 4]
   [1 3 3]]

  [[2 1 4]
   [0 4 2]
   [3 3 1]]

  [[1 4 4]
   [4 2 0]
   [3 1 2]]

  [[4 4 1]
   [2 0 0]
   [1 2 0]]

  [[4 1 0]
   [0 0 4]
   [2 0 2]]

  [[1 0 1]
   [0 4 0]
   [0 2 4]]]


 [[[4 3 4]
   [1 4 1]
   [2 1 4]]

  [[3 4 0]
   [4 1 3]
   [1 4 1]]

  [[4 0 4]
   [1 3 3]
   [4 1 2]]

  [[0 4 2]
   [3 3 1]
   [1 2 2]]

  [[4 2 0]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [130]:
class Symetric(np.ndarray):
    def __setitem__(self,index,value):
        i,j=index
        super(Symetric,self).__setitem__((i,j),value)
        super(Symetric,self).__setitem__((j,i),value)
def symetric(a):
    return np.asarray(a+a.T-np.diag(a.diagonal())).view(Symetric)
S=symetric(np.random.randint(0,10,(5,5)))
S[2,3]=42
print(S)

[[ 0  5  1  9  2]
 [ 5  0  7  7  7]
 [ 1  7  9 42  8]
 [ 9  7 42  3 10]
 [ 2  7  8 10  1]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [153]:
p,n=10,20
M=np.ones((p,n,n))
V=np.ones((p,n,1))
S=np.tensordot(M,V,axes=[[0,2],[0,1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [150]:
a=np.ones((16,16))
k=4
b=np.add.reduceat(np.add.reduceat(a,np.arange(0,a.shape[0],k),axis=0),
                                np.arange(0,a.shape[1],k),axis=1)
print(b)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [173]:
def iterated(a):
    N = (a[0:-2,0:-2] + a[0:-2,1:-1] + a[0:-2,2:] +
         a[1:-1,0:-2]                + a[1:-1,2:] +
         a[2:  ,0:-2] + a[2:  ,1:-1] + a[2:  ,2:])
    birth = (N==3) & (a[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (a[1:-1,1:-1]==1)
    a[...] = 0
    a[1:-1,1:-1][birth | survive] = 1
    return a
a= np.random.randint(0,2,(50,50))
for i in range(100):
    a = iterateds(a)
print(a)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [201]:
a=np.arange(10000)
n=5
print(a[np.argsort(a)[-n:]])
print(a[np.argpartition(-a,n)[:n]])

[9995 9996 9997 9998 9999]
[9995 9999 9998 9997 9996]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [222]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]  #converting array to numpy arr
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)    #making indices array with idx representation
    ix = ix.reshape(len(arrays), -1).T        #consolidating and taking transpose
    for n, arr in enumerate(arrays):        #seperating iterators and arrays 
        ix[:, n] = arrays[n][ix[:, n]]
    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [231]:
a=np.array([("hello",3.7,6.5),("world",7,4.9)])
r=np.core.records.fromarrays(a.T,names=('a','b','c'))    # passing three arrays by transpose and getting core dump 
print(r)

[('hello', '3.7', '6.5') ('world', '7', '4.9')]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [6]:
Z=np.arange(5)
print(np.power(Z,3))
print(Z*Z*Z)
print(np.einsum('i,i,i->i',Z,Z,Z))

[ 0  1  8 27 64]
[ 0  1  8 27 64]
[ 0  1  8 27 64]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [10]:
a=np.random.randint(0,5,(8,3))
b=np.random.randint(0,5,(2,2))
c=(a[..., np.newaxis, np.newaxis] == b)
rows = np.where(c.any((3,1)).all(1))[0]
print(rows)

[2 3 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [15]:
A= np.random.randint(0,5,(10,3))
print(A)
E = np.all(A[:,1:] == A[:,:-1], axis=1)
U = A[~E]
print(U)

[[1 3 4]
 [0 1 2]
 [1 0 4]
 [1 1 4]
 [4 0 0]
 [0 1 3]
 [0 0 2]
 [4 0 0]
 [0 2 1]
 [0 2 3]]
[[1 3 4]
 [0 1 2]
 [1 0 4]
 [1 1 4]
 [4 0 0]
 [0 1 3]
 [0 0 2]
 [4 0 0]
 [0 2 1]
 [0 2 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [26]:
a=np.array([1,2,3,4,5,8],dtype=np.uint8)
print(np.unpackbits(a[:,np.newaxis],axis=1))

[[0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 1]
 [0 0 0 0 1 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [31]:
A= np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(A).view(np.dtype((np.void, A.dtype.itemsize * A.shape[1])))
_, idx = np.unique(T, return_index=True)
uA = A[idx]
print(uA)

[[0 0 1]
 [0 1 0]
 [1 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [42]:
A = np.array([1,2,3,4,5])
B = np.array([10,20,30,40,50])
print(np.einsum('i->', A))       #sum
print(np.einsum('i,i->i', A, B)) # A * B
print(np.einsum('i,i', A, B))    # np.inner(A, B)
print(np.einsum('i,j->ij', A, B))    # np.outer(A, B)

15
[ 10  40  90 160 250]
550
[[ 10  20  30  40  50]
 [ 20  40  60  80 100]
 [ 30  60  90 120 150]
 [ 40  80 120 160 200]
 [ 50 100 150 200 250]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [50]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate_path
r_int = np.linspace(0, r.max(), 200) # regular_spaced_path
x_int = np.interp(r_int, r, x)       # integrate_path
y_int = np.interp(r_int, r, y)
#print(x_int)
#print(y_int)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [55]:
A = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(A, 1) == 0, axis=-1)
M &= (A.sum(axis=-1) == n)
print(A[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [58]:
A = np.random.randn(100) # random 1D array
N = 1000 # no.of bootstrap samples
idx = np.random.randint(0, A.size, (N, A.size))
means = A[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.22642927  0.16392608]
